applications/users/urls.py
from django.urls import path

# views 
from .views import SingInView
from .views import RegisterView
from .views import LogoutView

app_name = "users_app"

urlpatterns = [
    path("", SingInView.as_view(), name="login"),
    path("registro/", RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout")
]

todo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("applications.users.urls")),
    path("tareas/", include("applications.tasks.urls")),
    
]

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="sistema de tareas">
    <meta name="author" content="Miguel angel herrera vargas">
    <meta name="copyright" content="Miguel angel herrera vargas">
    <meta name="robots" content="index">
    <meta http-equiv="cache-control" content="no-cache">
    <script src="https://kit.fontawesome.com/ea233f63c4.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>todo list</title>
</head>
<body>
    
    {% include 'layouts/header.html' %}

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    
    {% include 'layouts/footer.html' %}   

    
    {% block scripts %}{% endblock scripts %}    
</body>
</html>

templates/layouts/footer.html
<footer>
    <p>
        Todos los derechos reservados &copy;
    </p>
</footer>

templates/layouts/header.html
<header>
    <div class="header">
        <h1>Todo List</h1>
        <nav>
            <ul>
                {% if user.is_anonymous %}
                <li><a href="{% url 'users_app:register' %}">Registrarse</a></li>
                <li><a href="{% url 'users_app:login' %}">Iniciar Sesion</a></li>
                {% else %}
                    <li class="user">{{user.name}} {{user.lastname}}</li>
                    <li><a href="{% url 'users_app:logout' %}">Salir</a></li>
                {% endif %}
                    
            </ul>
        </nav>
    </div>
</header>