applications/tasks/urls.py
from django.urls import path

# views 
from .views import TaskIndex
from .views import DeleteTaskView
from .views import UpdateTaskView

app_name = "tasks_app"

urlpatterns = [
    path("", TaskIndex.as_view(), name="index"),
    path("delete/<int:pk>", DeleteTaskView.as_view(), name="delete"),
    path("update/<int:pk>", UpdateTaskView.as_view(), name="update")
]

todo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("applications.users.urls")),
    path("tareas/", include("applications.tasks.urls")),
    
]

applications/tasks/models.py
from django.db import models
from django.db.models import Model

# models
from applications.users.models import User

# managers
from .managers import TaskManager

# Create your models here.
class Task(Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.TextField(max_length=255, null=False, blank=False)
    status = models.CharField(max_length=30, null=False, blank=False)
    objects = TaskManager()

applications/tasks/forms.py
from django import forms
from django.forms import Form


class TaskForm(Form):
    """
        Clase para el formulario de tareas
    """
    tasks = forms.CharField(
        label= "Tarea",
        widget=forms.Textarea({"rows":"5"})
    )
    
    def clean_tasks(self):
        task = self.cleaned_data["tasks"]
        if len(task) < 8: 
            self.add_error("tasks", "El campo debe contener mas de 8 caracteres")
        return task

applications/tasks/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.views.generic import FormView
from django.views.generic import ListView
from django.views.generic import View
from django.urls import reverse_lazy

# models
from .models import Task
from applications.users.models import User

# forms
from .forms import TaskForm

# permissions
from .permissions import TaskPermisionMixin


# Create your views here.
class TaskIndex(TaskPermisionMixin, ListView, FormView):
    # TaskIndex:
    # muestra la vista del sistema despues de loguearse
    # extrae las tareas de registradas por el usuario
    # procesa el formulario para registrar las tareas del usuario
    template_name = "tasks/index.html"
    form_class = TaskForm
    success_url = reverse_lazy("tasks_app:index")
    paginate_by = 5
    model = None
    context_object_name = "tasks"
    
    def get_context_data(self, **kwargs):
        user_pk =  self.request.user.id
        user = User.objects.get_user(user_pk)
        context = super().get_context_data(**kwargs)
        context["user"] =  user
        return context
    
    def form_valid(self, form):
        user = self.request.user
        task = form.cleaned_data["tasks"]
        Task.objects.add_task(task, user)
        return super().form_valid(form)
    
    def get_queryset(self):
        user_pk =  self.request.user.id
        user = User.objects.get_user(user_pk)
        tasks = Task.objects.all_task(user).order_by("-status")
        return tasks
    

class DeleteTaskView(TaskPermisionMixin, View):
    # DeleteTaskView: 
    # procesa la logica para eliminar dicha tarea por el id 
    # sin importar el estado de la tarea
    login_url = reverse_lazy("users_app:logout")
    
    def get(self, request, *args, **kwargs):
        pk = self.kwargs["pk"]
        Task.objects.delete_task(pk)
        return HttpResponseRedirect(reverse_lazy("tasks_app:index"))
    
    
class UpdateTaskView(TaskPermisionMixin, View):
    # UpdateTaskView:
    # Actualizar el estado de la tarea de Pendiente a Completada
    # mediante el pk
    login_url = reverse_lazy("users_app:logout")
    
    def get(self, request, *args, **kwargs):
        pk = self.kwargs["pk"]
        Task.objects.update_task(pk)
        return HttpResponseRedirect(reverse_lazy("tasks_app:index"))

templates/tasks/index.html
{% extends '../layouts/base.html' %}



{% block content %}
<form method="POST" class="form">
    <div class="form-header">
        <h3>Agregar Tarea</h3>
        <div class="add-tasks">
            <label for="add">+</label>
            <input type="checkbox" id="add">
        </div>
        </div>
        <div class="form-body">
            {% csrf_token %}
            <div class="task-control">
                {{form.tasks}}
                <button type="submit">Agregar</button>
            </div>
            {{ form.errors.tasks }}
        </div>
    </form>
    
    
    <ul class="list-tasks">
        {% for task in tasks %}
            <li {% if task.status == 'Pendiente'%} class="li-danger" {% else %} class="li-success" {% endif %}>
                {{task.task}}
                <div class="task-actions">
                    
                    {% if task.status == "Pendiente"  %}
                        <a href="{% url 'tasks_app:update' task.id%}" class="success"><i class="fa-solid fa-circle-check"></i></a>
                    {% endif %}
                    <a href="{% url 'tasks_app:delete' task.id %}" class="danger"><i class="fa-solid fa-circle-minus"></i></a>
                </div>
            </li>
        {% endfor %}
    </ul>
            

    
    {% if is_paginated %}
        <nav class="pagination">
            <ul>
                
                {% if page_obj.has_previous %}
                    <li><a href="?page={{page_obj.previous_page_number}}">Atras</a></li>
                {% endif %}
                
                
                {% for page in paginator.page_range %}
                
                    {% if page == page_obj.number %}
                        <li><a class="selected">{{page}}</a></li>
                    {% else %}
                        <li><a href="?page={{page}}">{{page}}</a></li>
                    {% endif %}
                    

                {% endfor %}
                    
                
                
                {% if  page_obj.has_next%}
                    <li><a href="?page={{page_obj.next_page_number}}">Siguiente</a></li>
                    
                {% endif %}
                    
            </ul>
        </nav>
    {% endif %}
{% endblock content %}


{% block scripts %}
    {% load static %}
    <script src="{% static 'js/task.js' %}"></script>
{% endblock scripts %}
    
    